sonar.organization=pierre-mariemarchio
sonar.projectKey=Pierre-MarieMarchio_portfolio
sonar.projectName=portfolio

sonar.sources=src/app,scripts
sonar.tests=src
sonar.test.inclusions=src/**/*.spec.ts,src/testing/**/*.ts
sonar.exclusions=src/**/*.spec.ts,src/testing/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=scripts/**,src/app/**/index.ts,src/app/**/*.data.ts,src/app/app.config*.ts,src/main*.ts

sonar.cpd.exclusions=src/app/**/*.data.ts

sonar.issue.ignore.multicriteria=e1,e2,e3,e4,e5,e6

sonar.issue.ignore.multicriteria.e1.ruleKey=typescript:S7773
sonar.issue.ignore.multicriteria.e1.resourceKey=src/**

sonar.issue.ignore.multicriteria.e2.ruleKey=Web:S6822
sonar.issue.ignore.multicriteria.e2.resourceKey=**/card-carousel.component.html

sonar.issue.ignore.multicriteria.e3.ruleKey=Web:S6819
sonar.issue.ignore.multicriteria.e3.resourceKey=**/segmented.component.html

sonar.issue.ignore.multicriteria.e4.ruleKey=Web:S6819
sonar.issue.ignore.multicriteria.e4.resourceKey=**/language-switch.component.html

sonar.issue.ignore.multicriteria.e5.ruleKey=typescript:S7754
sonar.issue.ignore.multicriteria.e5.resourceKey=**/observatory-page.component.ts

sonar.issue.ignore.multicriteria.e6.ruleKey=Web:S6825
sonar.issue.ignore.multicriteria.e6.resourceKey=**/space-scene.component.html
