// @ts-check
/** @type {Record<string, string>} */
export const ROLE_OF = {
  component: 'components',
  directive: 'directives',
  pipe: 'pipes',
  service: 'services',
  manager: 'states',
  state: 'states',
  action: 'states',
  updater: 'states',
  effect: 'states',
  port: 'ports',
  provider: 'providers',
  guard: 'guards',
  resolver: 'resolvers',
  interceptor: 'interceptors',
  validator: 'validators',
  strategy: 'strategies',
  rules: 'rules',
  helper: 'helpers',
  signal: 'signals',
  model: 'models',
  data: 'data',
  engine: 'engine',
  motion: 'motions',
  renderer: 'renderers',
  tracker: 'trackers',
  worker: 'engine',
};

/** @type {Record<string, string[]>} */
export const EXTENSIONS_OF = {
  component: ['ts', 'html', 'scss'],
  data: ['ts', 'json'],
};

export const CLASS_SUFFIXES = new Set([
  'component',
  'directive',
  'pipe',
  'service',
  'manager',
  'state',
  'effect',
  'strategy',
  'engine',
  'motion',
  'renderer',
  'tracker',
]);

/** @type {Record<string, string[]>} */
export const ROLES_IN = {
  core: [
    'services',
    'ports',
    'strategies',
    'interceptors',
    'models',
    'rules',
    'helpers',
    'signals',
  ],
  'shared/ui': [
    'components',
    'directives',
    'pipes',
    'services',
    'validators',
    'signals',
    'ports',
    'models',
    'data',
  ],
  feature: [
    'components',
    'directives',
    'pipes',
    'services',
    'states',
    'ports',
    'validators',
    'rules',
    'models',
    'data',
  ],
  'shared/windows': [
    'components',
    'directives',
    'services',
    'rules',
    'trackers',
    'models',
    'ports',
  ],
  'shared/mobile-nav': [
    'components',
    'directives',
    'services',
    'rules',
    'models',
    'ports',
  ],
  'shared/space-scene': [
    'components',
    'directives',
    'services',
    'engine',
    'rules',
    'trackers',
    'models',
    'ports',
  ],
  'features/common': ['ports', 'models'],
  i18n: [
    'services',
    'providers',
    'guards',
    'resolvers',
    'models',
    'rules',
    'data',
  ],
  pages: [],
};

export const ENGINE_ZONES = new Set(['shared/space-scene']);
